name: Deploy UI to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "ui-careerpath/**"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui-careerpath # Default working directory for ALL steps

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Add a step to debug what's in the build directory
      - name: Debug dist directory
        run: ls -la dist

      # Create .nojekyll file
      - name: Create .nojekyll file
        run: touch dist/.nojekyll

      # Deploy with a more explicit approach
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ui-careerpath/dist # Full path from workspace root
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
