name: Deploy UI to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "ui-careerpath/**"

# Add this permissions block
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui-careerpath

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Add this line for cleaner git state

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ui-careerpath/dist
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }} # Add this to explicitly use the GitHub token
