name: Deploy UI to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "ui-careerpath/**"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build UI
        run: |
          cd ui-careerpath
          npm ci
          npm run build

      - name: Prepare deployment
        run: |
          # Create a clean deployment directory
          mkdir -p /tmp/deploy

          # Copy only the build output to the deployment directory
          cp -r ui-careerpath/dist/* /tmp/deploy/

          # Create .nojekyll file to disable Jekyll processing
          touch /tmp/deploy/.nojekyll

          # Debug: List what we're about to deploy
          echo "Contents of deployment directory:"
          ls -la /tmp/deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/deploy
          force_orphan: true # Create a new history for the gh-pages branch
