name: Deploy UI to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "ui-careerpath/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui-careerpath # Set default working directory for all run steps

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          # Disable caching for now to eliminate that source of errors

      - name: Install dependencies
        run: npm ci
        # No need for cd command now with working-directory set

      - name: Build
        run: npm run build
        # No need for cd command now with working-directory set

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ui-careerpath/dist
          branch: gh-pages
